import type { Metadata } from "next";
import "./globals.css";
import "@/styles/styles.css";
import "@/styles/table.css";
import "@/styles/animation.css"


export const metadata: Metadata = {
  title: "Papiverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </head>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
