import type { Metadata } from "next";
import { Figtree, Nunito } from "next/font/google";
import "./globals.css";
import "@/styles/styles.css";
import "@/styles/table.css";
import "@/styles/animation.css"
import { AuthProvider } from "@/hooks/use-auth";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppCanvas } from "@/components/shared/AppCanvas";
import { Toaster } from "@/components/ui/toaster";

const figtree = Figtree({
	subsets: ["latin"],
	variable: "--font-figtree",
});

const nunito = Nunito({
	subsets: ["latin"],
	variable: "--font-nunito",
});


export const metadata: Metadata = {
	title: "Krispy Papi",
	description: "Generated by create next app",
	icons: {
		icon: "/images/favicon.png",
		shortcut: "/images/favicon.png",
		apple: "/images/favicon.png",
	},
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${figtree.variable} ${nunito.variable} antialiased`}
			>
				<AuthProvider>
				<SidebarProvider className="bg-slate-100 max-w-[2560px] mx-auto">
					<Toaster position="top-center" />
					<AppCanvas>{ children }</AppCanvas>
				</SidebarProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
