import type { Metadata } from "next";
import "./globals.css";
import "@/styles/styles.css";
import "@/styles/table.css";
import "@/styles/animation.css"
import { AuthProvider } from "@/hooks/use-auth";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/AppSidebar";
import { AppCanvas } from "@/components/shared/AppCanvas";
import { Toaster } from "@/components/ui/toaster";


export const metadata: Metadata = {
  title: "Papiverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </head>
      <body
        className={`antialiased`}
      >
        <AuthProvider>
          <SidebarProvider className="bg-slate-100 max-w-[2560px] mx-auto">
            <Toaster position="top-center" />
            <AppCanvas>{ children }</AppCanvas>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
